/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialog;

/**
 *
 * @author Dekwaii
 */

import controller.SepatuController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sepatu;
import view.PanelStokMasuk;

public class DialogSepatu extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogSepatu.class.getName());

    private final SepatuController sepatuController = new SepatuController();
    private DefaultTableModel tableModel;
    private PanelStokMasuk panelStokMasuk;
    
    public DialogSepatu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DialogSepatu(java.awt.Frame parent, boolean modal, PanelStokMasuk panelStokMasuk) {
        super(parent, modal);
        this.panelStokMasuk = panelStokMasuk;
        initComponents();
        
        loadTableSepatu(null);
        
        // Filter real-time saat user mengetik
        txtCariSepatu.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filterTabel(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filterTabel(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filterTabel(); }
        });

        // Double click baris = langsung pilih
        tableDaftarSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    pilihData();
                }
            }
        });
    }
    
    private void loadTableSepatu(String keyword) {
        String[] kolom = {"ID", "Nama Sepatu", "Brand", "Ukuran"};
        tableModel = new DefaultTableModel(kolom, 0) {
            public boolean isCellEditable(int row, int col) { return false; }
        };

        List<Sepatu> list = sepatuController.getAllSepatu();
        for (Sepatu s : list) {
            if (keyword == null || keyword.isEmpty() ||
                s.getNamaSepatu().toLowerCase().contains(keyword.toLowerCase()) ||
                s.getBrand().toLowerCase().contains(keyword.toLowerCase())) {
                tableModel.addRow(new Object[]{
                    s.getIdSepatu(),
                    s.getNamaSepatu(),
                    s.getBrand(),
                    s.getUkuran()
                });
            }
        }
        tableDaftarSepatu.setModel(tableModel);
    }
    
    private void filterTabel() {
        loadTableSepatu(txtCariSepatu.getText().trim());
    }
    
    private void pilihData() {
        int baris = tableDaftarSepatu.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Sepatu terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSepatu = tableModel.getValueAt(baris, 0).toString();
        String namaSepatu = tableModel.getValueAt(baris, 1).toString();

        // Kirim balik ke PanelStokMasuk
        panelStokMasuk.setSelectedSepatu(idSepatu, namaSepatu);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCari = new javax.swing.JPanel();
        txtCariSepatu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelDaftarSepatu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDaftarSepatu = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btnPilihSepatu = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        panelCari.setPreferredSize(new java.awt.Dimension(600, 100));

        txtCariSepatu.addActionListener(this::txtCariSepatuActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Ketik Nama Sepatu");

        javax.swing.GroupLayout panelCariLayout = new javax.swing.GroupLayout(panelCari);
        panelCari.setLayout(panelCariLayout);
        panelCariLayout.setHorizontalGroup(
            panelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCariLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelCariLayout.setVerticalGroup(
            panelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCariLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelCari, java.awt.BorderLayout.NORTH);

        panelDaftarSepatu.setPreferredSize(new java.awt.Dimension(600, 290));
        panelDaftarSepatu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDaftarSepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Sepatu", "Brand", "Size"
            }
        ));
        jScrollPane1.setViewportView(tableDaftarSepatu);

        panelDaftarSepatu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 540, 270));

        getContentPane().add(panelDaftarSepatu, java.awt.BorderLayout.LINE_START);

        panelButton.setPreferredSize(new java.awt.Dimension(600, 80));
        panelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPilihSepatu.setBackground(new java.awt.Color(6, 25, 81));
        btnPilihSepatu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPilihSepatu.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihSepatu.setText("Pilih Data");
        btnPilihSepatu.addActionListener(this::btnPilihSepatuActionPerformed);
        panelButton.add(btnPilihSepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 164, 39));

        btnBatal.setBackground(new java.awt.Color(204, 0, 0));
        btnBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        panelButton.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 20, 110, 39));

        getContentPane().add(panelButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariSepatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariSepatuActionPerformed

    private void btnPilihSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihSepatuActionPerformed
        pilihData();
    }//GEN-LAST:event_btnPilihSepatuActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogSepatu dialog = new DialogSepatu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilihSepatu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelDaftarSepatu;
    private javax.swing.JTable tableDaftarSepatu;
    private javax.swing.JTextField txtCariSepatu;
    // End of variables declaration//GEN-END:variables
}
