/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dekwaii
 */

import javax.swing.*;
import java.awt.*;
import model.User;

public class MainDashboardFrame extends javax.swing.JFrame {
    
    private User userLogon;
    private String roleUserLogedIn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboardFrame.class.getName());

    /**
     * Creates new form MainDashboardFrame
     */
    public MainDashboardFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        // 2. JALAN TENGAH: Paksa aplikasi otomatis Maximize (Full Window tetapi tidak menutupi Taskbar)
//        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    private void setMenuColor(JButton tombolAktif){
        JButton[] semuaTombol = {btnDashboard, btnKelolaData, btnStokMasuk, btnReport, btnAboutUs};
        
        for(JButton btn : semuaTombol){
            if(btn == tombolAktif){
                btn.setSelected(true);
            
                // 2 Baris Sakti: Paksa Swing untuk menggambar warna putih solid secara absolut
                btn.setOpaque(true); 
                btn.setContentAreaFilled(true); 

                btn.setBackground(Color.WHITE);
                btn.setForeground(Color.BLACK); // Warna teks biru tua #061951
            } else {
                btn.setSelected(false);

                // Kembalikan tombol lain menjadi transparan penuh menyatu dengan sidebar
                btn.setOpaque(false);
                btn.setContentAreaFilled(false);
                
                btn.setForeground(Color.WHITE);
            }
        }
    }
    
    public void setHakAkses(User userResult){
        this.userLogon = userResult;
        this.roleUserLogedIn = userResult.getRole();
        
        lblRole.setText(userLogon.getRole() + " - " + userLogon.getUsername());
    
        // 2. Filter menu berdasarkan role
        if (userLogon.getRole().equalsIgnoreCase("Super Admin")) {
            // Tampilkan menu Super Admin
            btnDashboard.setVisible(false);
            btnKelolaData.setVisible(true);
            btnReport.setVisible(true);
            btnAboutUs.setVisible(true);
            btnStokMasuk.setVisible(false);

        } else if (userLogon.getRole().equalsIgnoreCase("Admin Gudang")) {
            // Tampilkan menu Admin Gudang
            btnDashboard.setVisible(false);
            btnKelolaData.setVisible(true);
            btnStokMasuk.setVisible(true);
            btnReport.setVisible(false);
            btnAboutUs.setVisible(false);
            
            
        }
        // Default awal saat masuk aplikasi: buka Dashboard
        btnKelolaDataActionPerformed(null);
        
        if (panelKelolaData != null) {
            panelKelolaData.setHakAksesPanel(this.roleUserLogedIn);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelSidebar = new javax.swing.JPanel();
        InventifyLogo = new javax.swing.JLabel();
        panelContainerMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnKelolaData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnStokMasuk = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAboutUs = new javax.swing.JButton();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        panelKanan = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblJudulHalaman = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelKontenUtama = new javax.swing.JPanel();
        panelDashboard = new view.PanelDashboard();
        panelKelolaData = new view.PanelKelolaData();
        panelStokMasuk = new view.PanelStokMasuk();
        panelReport = new view.PanelReport();
        panelAboutUs = new view.PanelAboutUs();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 780));

        panelSidebar.setBackground(new java.awt.Color(6, 25, 81));
        panelSidebar.setPreferredSize(new java.awt.Dimension(240, 700));
        panelSidebar.setLayout(new java.awt.BorderLayout());

        InventifyLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InventifyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventify-logo.png"))); // NOI18N
        InventifyLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InventifyLogo.setPreferredSize(new java.awt.Dimension(240, 80));
        panelSidebar.add(InventifyLogo, java.awt.BorderLayout.NORTH);

        panelContainerMenu.setBackground(new java.awt.Color(6, 25, 81));
        panelContainerMenu.setMaximumSize(new java.awt.Dimension(142, 100));
        panelContainerMenu.setPreferredSize(new java.awt.Dimension(240, 500));
        panelContainerMenu.setLayout(new javax.swing.BoxLayout(panelContainerMenu, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(6, 25, 81));
        jPanel1.setMaximumSize(new java.awt.Dimension(520, 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(60, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelContainerMenu.add(jPanel1);

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_dashboard_light.png"))); // NOI18N
        btnDashboard.setText("  Dashboard");
        btnDashboard.setBorderPainted(false);
        buttonGroup1.add(btnDashboard);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDashboard.setMargin(new java.awt.Insets(2, 18, 3, 14));
        btnDashboard.setMaximumSize(new java.awt.Dimension(146, 35));
        btnDashboard.setMinimumSize(new java.awt.Dimension(146, 28));
        btnDashboard.setPreferredSize(new java.awt.Dimension(240, 40));
        btnDashboard.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_dashboard_dark.png"))); // NOI18N
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        panelContainerMenu.add(btnDashboard);

        jPanel2.setBackground(new java.awt.Color(6, 25, 81));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelContainerMenu.add(jPanel2);

        btnKelolaData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKelolaData.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_keloladata_light.png"))); // NOI18N
        btnKelolaData.setText("  Kelola Data");
        btnKelolaData.setBorderPainted(false);
        buttonGroup1.add(btnKelolaData);
        btnKelolaData.setContentAreaFilled(false);
        btnKelolaData.setFocusPainted(false);
        btnKelolaData.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnKelolaData.setMargin(new java.awt.Insets(2, 18, 3, 14));
        btnKelolaData.setMaximumSize(new java.awt.Dimension(146, 35));
        btnKelolaData.setMinimumSize(new java.awt.Dimension(146, 28));
        btnKelolaData.setPreferredSize(new java.awt.Dimension(240, 40));
        btnKelolaData.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_keloladata_dark.png"))); // NOI18N
        btnKelolaData.addActionListener(this::btnKelolaDataActionPerformed);
        panelContainerMenu.add(btnKelolaData);

        jPanel3.setBackground(new java.awt.Color(6, 25, 81));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelContainerMenu.add(jPanel3);

        btnStokMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStokMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnStokMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_stokmasuk_light.png"))); // NOI18N
        btnStokMasuk.setText("  Stok Masuk");
        btnStokMasuk.setBorderPainted(false);
        buttonGroup1.add(btnStokMasuk);
        btnStokMasuk.setContentAreaFilled(false);
        btnStokMasuk.setFocusPainted(false);
        btnStokMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnStokMasuk.setMargin(new java.awt.Insets(2, 18, 3, 14));
        btnStokMasuk.setMaximumSize(new java.awt.Dimension(146, 35));
        btnStokMasuk.setPreferredSize(new java.awt.Dimension(240, 40));
        btnStokMasuk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_stokmasuk_dark.png"))); // NOI18N
        btnStokMasuk.addActionListener(this::btnStokMasukActionPerformed);
        panelContainerMenu.add(btnStokMasuk);

        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_report_light.png"))); // NOI18N
        btnReport.setText("  Report        ");
        btnReport.setBorderPainted(false);
        buttonGroup1.add(btnReport);
        btnReport.setContentAreaFilled(false);
        btnReport.setFocusPainted(false);
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnReport.setMargin(new java.awt.Insets(2, 18, 3, 14));
        btnReport.setMaximumSize(new java.awt.Dimension(146, 35));
        btnReport.setMinimumSize(new java.awt.Dimension(146, 28));
        btnReport.setPreferredSize(new java.awt.Dimension(240, 40));
        btnReport.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_report_dark.png"))); // NOI18N
        btnReport.addActionListener(this::btnReportActionPerformed);
        panelContainerMenu.add(btnReport);

        jPanel5.setBackground(new java.awt.Color(6, 25, 81));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelContainerMenu.add(jPanel5);

        btnAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_aboutus_light.png"))); // NOI18N
        btnAboutUs.setText("  About Us   ");
        btnAboutUs.setBorderPainted(false);
        buttonGroup1.add(btnAboutUs);
        btnAboutUs.setContentAreaFilled(false);
        btnAboutUs.setFocusPainted(false);
        btnAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAboutUs.setMargin(new java.awt.Insets(2, 18, 3, 14));
        btnAboutUs.setMaximumSize(new java.awt.Dimension(146, 35));
        btnAboutUs.setMinimumSize(new java.awt.Dimension(146, 28));
        btnAboutUs.setPreferredSize(new java.awt.Dimension(240, 40));
        btnAboutUs.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_aboutus_dark.png"))); // NOI18N
        btnAboutUs.addActionListener(this::btnAboutUsActionPerformed);
        panelContainerMenu.add(btnAboutUs);

        panelSidebar.add(panelContainerMenu, java.awt.BorderLayout.CENTER);

        panelLogout.setBackground(new java.awt.Color(6, 25, 81));
        panelLogout.setMaximumSize(new java.awt.Dimension(180, 70));
        panelLogout.setMinimumSize(new java.awt.Dimension(180, 70));
        panelLogout.setPreferredSize(new java.awt.Dimension(240, 70));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_logout.png"))); // NOI18N
        btnLogout.setText("  LogOut");
        btnLogout.setAlignmentX(0.5F);
        btnLogout.setBorderPainted(false);
        btnLogout.setMaximumSize(new java.awt.Dimension(180, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(180, 40));
        btnLogout.setPreferredSize(new java.awt.Dimension(180, 40));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        panelLogout.add(btnLogout);

        panelSidebar.add(panelLogout, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelSidebar, java.awt.BorderLayout.WEST);

        panelKanan.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setPreferredSize(new java.awt.Dimension(960, 60));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudulHalaman.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblJudulHalaman.setText("DASHBOARD");
        panelHeader.add(lblJudulHalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 180, 30));

        lblRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Super Admin - Dekwai");
        panelHeader.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_user.png"))); // NOI18N
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        panelKanan.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelKontenUtama.setLayout(new java.awt.CardLayout());

        panelDashboard.setPreferredSize(new java.awt.Dimension(960, 680));
        panelKontenUtama.add(panelDashboard, "panelDashboard");
        panelKontenUtama.add(panelKelolaData, "panelKelolaData");

        panelStokMasuk.setPreferredSize(new java.awt.Dimension(960, 680));
        panelKontenUtama.add(panelStokMasuk, "panelStokMasuk");

        panelReport.setPreferredSize(new java.awt.Dimension(960, 680));
        panelKontenUtama.add(panelReport, "panelReport");
        panelKontenUtama.add(panelAboutUs, "panelAboutUs");

        panelKanan.add(panelKontenUtama, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelKanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        setMenuColor(btnDashboard);
        lblJudulHalaman.setText("DASHBOARD");
        
        CardLayout cl = (CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "panelDashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDataActionPerformed
        setMenuColor(btnKelolaData);
        lblJudulHalaman.setText("KELOLA DATA");
      
        CardLayout cl = (CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "panelKelolaData");
    }//GEN-LAST:event_btnKelolaDataActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        setMenuColor(btnReport);
        lblJudulHalaman.setText("REPORT");
        
        CardLayout cl = (CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "panelReport");
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnStokMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokMasukActionPerformed
        setMenuColor(btnStokMasuk);
        lblJudulHalaman.setText("STOK MASUK");
        
        CardLayout cl = (CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "panelStokMasuk");
    }//GEN-LAST:event_btnStokMasukActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        setMenuColor(btnAboutUs);
        lblJudulHalaman.setText("ABOUT US");
        
        CardLayout cl = (CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "panelAboutUs");
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar dari sistem Inventify?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION);
            
        if (konfirmasi == JOptionPane.YES_OPTION) {
            // 2. Buka kembali frame login kamu (sesuaikan nama class LoginFrame milikmu)
            LoginFrame login = new LoginFrame();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            // 3. Tutup total frame dashboard saat ini
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InventifyLogo;
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKelolaData;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStokMasuk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblJudulHalaman;
    private javax.swing.JLabel lblRole;
    private view.PanelAboutUs panelAboutUs;
    private javax.swing.JPanel panelContainerMenu;
    private view.PanelDashboard panelDashboard;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelKanan;
    private view.PanelKelolaData panelKelolaData;
    private javax.swing.JPanel panelKontenUtama;
    private javax.swing.JPanel panelLogout;
    private view.PanelReport panelReport;
    private javax.swing.JPanel panelSidebar;
    private view.PanelStokMasuk panelStokMasuk;
    // End of variables declaration//GEN-END:variables
}
