/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.SepatuController;
import controller.StokMasukController;
import controller.SupplierController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.StokMasuk;
import util.TableDecorator;

/**
 *
 * @author Dekwaii
 */
public class PanelStokMasuk extends javax.swing.JPanel {

    private final StokMasukController stokMasukController = new StokMasukController();
    private final SupplierController supplierController = new SupplierController();
    private final SepatuController sepatuController = new SepatuController();
    private DefaultTableModel tableModelStokMasuk;

    // Menyimpan ID asli hasil pilih dari dialog
    private int selectedSupplierIdForStok = -1;
    private String selectedSepatuIdForStok = "";
    private int selectedIdMasuk = -1;
    private List<StokMasuk> listStokMasukSekarang;
    
    public PanelStokMasuk() {
        initComponents();
        loadTableStokMasuk();

        // Listener otomatis hitung total saat jumlah atau harga berubah
        txtJumlahStok.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
        });

        txtHargaBeli.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { hitungTotalHarga(); }
        });

        // TextField supplier & sepatu tidak bisa diketik manual
        txtStokSupplier.setEditable(false);
        txtStokSepatu.setEditable(false);
    }
    
    // Dipanggil dari DialogSupplier setelah user pilih supplier
    public void setSelectedSupplier(int idSupplier, String namaSupplier) {
        this.selectedSupplierIdForStok = idSupplier;
        txtStokSupplier.setText(namaSupplier);
    }
    
    // Dipanggil dari DialogSepatu setelah user pilih sepatu
    public void setSelectedSepatu(String idSepatu, String namaSepatu) {
        this.selectedSepatuIdForStok = idSepatu;
        txtStokSepatu.setText(namaSepatu);
    }
    
    private void loadTableStokMasuk() {
        String[] judulKolom = {"Tanggal", "Nama Supplier", "Nama Sepatu", "Stok", "Harga/pcs", "Total Harga"};
        tableModelStokMasuk = new DefaultTableModel(judulKolom, 0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");

        listStokMasukSekarang = stokMasukController.getAllStokMasuk(); // simpan buat referensi klik row
        for (StokMasuk sm : listStokMasukSekarang) {
            Object[] rowData = {
                sdf.format(sm.getTanggal()),
                sm.getNamaSupplier(),
                sm.getNamaSepatu(),
                sm.getJumlah(),
                String.format("%,.0f", sm.getHargaBeli()),
                String.format("%,.0f", sm.getTotalHarga())
            };
            tableModelStokMasuk.addRow(rowData);
        }
        tableStokMasuk.setModel(tableModelStokMasuk);
        
        TableDecorator.decorateTableStok(tableStokMasuk);
    }
    
    private void clearFormStokMasuk() {
        txtStokSupplier.setText("");
        txtStokSepatu.setText("");
        txtJumlahStok.setText("");
        txtHargaBeli.setText("");
        selectedSupplierIdForStok = -1;
        selectedSepatuIdForStok = "";
        txtStokSupplier.setEditable(true);  
        txtStokSepatu.setEditable(true);
    }
    
    private void hitungTotalHarga() {
        try {
            int jumlah = Integer.parseInt(txtJumlahStok.getText().trim());
            double harga = Double.parseDouble(txtHargaBeli.getText().trim());
            double total = jumlah * harga;
            // Total hanya ditampilkan di tabel setelah submit, bukan di form
            // Bisa juga tampilkan di label kalau mau preview
        } catch (NumberFormatException e) {
            // Abaikan, user masih mengetik
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormStok = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStokSupplier = new javax.swing.JTextField();
        btnInputSupplier = new javax.swing.JButton();
        txtStokSepatu = new javax.swing.JTextField();
        btnInputSepatu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJumlahStok = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        btnTambahStok = new javax.swing.JButton();
        btnEditStok = new javax.swing.JButton();
        btnDeleteStok = new javax.swing.JButton();
        panelTableStok = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStokMasuk = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(960, 680));
        setMinimumSize(new java.awt.Dimension(960, 680));
        setLayout(new java.awt.BorderLayout());

        panelFormStok.setPreferredSize(new java.awt.Dimension(960, 270));
        panelFormStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Form Input Stok Masuk");
        panelFormStok.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Nama Supplier");
        panelFormStok.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Nama Sepatu");
        panelFormStok.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, -1));
        panelFormStok.add(txtStokSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 40));

        btnInputSupplier.setBackground(new java.awt.Color(255, 187, 0));
        btnInputSupplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnInputSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnInputSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_tambah.png"))); // NOI18N
        btnInputSupplier.addActionListener(this::btnInputSupplierActionPerformed);
        panelFormStok.add(btnInputSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 50, 40));
        panelFormStok.add(txtStokSepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 40));

        btnInputSepatu.setBackground(new java.awt.Color(21, 68, 208));
        btnInputSepatu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnInputSepatu.setForeground(new java.awt.Color(255, 255, 255));
        btnInputSepatu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_tambah.png"))); // NOI18N
        btnInputSepatu.addActionListener(this::btnInputSepatuActionPerformed);
        panelFormStok.add(btnInputSepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Harga beli       ");
        panelFormStok.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Stok    ");
        panelFormStok.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 100, -1));
        panelFormStok.add(txtJumlahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, 40));
        panelFormStok.add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, 40));

        btnTambahStok.setBackground(new java.awt.Color(6, 25, 81));
        btnTambahStok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnTambahStok.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_tambah.png"))); // NOI18N
        btnTambahStok.setText("Tambah Stok");
        btnTambahStok.addActionListener(this::btnTambahStokActionPerformed);
        panelFormStok.add(btnTambahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 150, 50));

        btnEditStok.setBackground(new java.awt.Color(255, 187, 0));
        btnEditStok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEditStok.setForeground(new java.awt.Color(255, 255, 255));
        btnEditStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_edit.png"))); // NOI18N
        btnEditStok.setText("Edit Stok");
        btnEditStok.addActionListener(this::btnEditStokActionPerformed);
        panelFormStok.add(btnEditStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 50));

        btnDeleteStok.setBackground(new java.awt.Color(241, 69, 69));
        btnDeleteStok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDeleteStok.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_delete.png"))); // NOI18N
        btnDeleteStok.setText("Delete Stok");
        btnDeleteStok.addActionListener(this::btnDeleteStokActionPerformed);
        panelFormStok.add(btnDeleteStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 150, 50));

        add(panelFormStok, java.awt.BorderLayout.NORTH);

        panelTableStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableStokMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStokMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStokMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStokMasuk);

        panelTableStok.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 900, 380));

        add(panelTableStok, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputSupplierActionPerformed
        dialog.DialogSupplier dialogSupplier = new dialog.DialogSupplier(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, this
        );
        dialogSupplier.setVisible(true);
    }//GEN-LAST:event_btnInputSupplierActionPerformed

    private void btnTambahStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahStokActionPerformed
        // Validasi supplier
        if (selectedSupplierIdForStok == -1) {
            JOptionPane.showMessageDialog(this, "Pilih supplier terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi sepatu
        if (selectedSepatuIdForStok.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih sepatu terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi jumlah & harga
        String jumlahStr = txtJumlahStok.getText().trim();
        String hargaStr = txtHargaBeli.getText().trim();

        if (jumlahStr.isEmpty() || hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah stok dan harga beli wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int jumlah;
        double harga;
        try {
            jumlah = Integer.parseInt(jumlahStr);
            harga = Double.parseDouble(hargaStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah stok dan harga beli harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jumlah <= 0 || harga <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah stok dan harga beli harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double totalHarga = jumlah * harga;

        StokMasuk sm = new StokMasuk(selectedSupplierIdForStok, selectedSepatuIdForStok, jumlah, harga, totalHarga);
        boolean berhasil = stokMasukController.tambahStokMasuk(sm);

        if (berhasil) {
            JOptionPane.showMessageDialog(this, "Stok berhasil ditambahkan!");
            clearFormStokMasuk();
            loadTableStokMasuk();
        }
    
    }//GEN-LAST:event_btnTambahStokActionPerformed

    private void btnInputSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputSepatuActionPerformed
        dialog.DialogSepatu dialogSepatu = new dialog.DialogSepatu(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, this
        );
        dialogSepatu.setVisible(true);
    }//GEN-LAST:event_btnInputSepatuActionPerformed

    private void btnEditStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStokActionPerformed
        if (selectedIdMasuk == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data stok yang mau diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String jumlahStr = txtJumlahStok.getText().trim();
        String hargaStr = txtHargaBeli.getText().trim();

        if (jumlahStr.isEmpty() || hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Stok dan Harga Beli wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int jumlah;
        double harga;
        try {
            jumlah = Integer.parseInt(jumlahStr);
            harga = Double.parseDouble(hargaStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah Stok dan Harga Beli harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jumlah <= 0 || harga <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah Stok dan Harga Beli harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean berhasil = stokMasukController.editStokMasuk(selectedIdMasuk, jumlah, harga);

        if (berhasil) {
            JOptionPane.showMessageDialog(this, "Data stok berhasil diupdate!");
            clearFormStokMasuk();
            loadTableStokMasuk();
        }
    }//GEN-LAST:event_btnEditStokActionPerformed

    private void tableStokMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStokMasukMouseClicked
        int row = tableStokMasuk.getSelectedRow();
        if (row != -1 && listStokMasukSekarang != null) {
            StokMasuk sm = listStokMasukSekarang.get(row);
            selectedIdMasuk = sm.getIdMasuk();

            txtStokSupplier.setText(sm.getNamaSupplier());
            txtStokSepatu.setText(sm.getNamaSepatu());
            txtJumlahStok.setText(String.valueOf(sm.getJumlah()));
            txtHargaBeli.setText(String.valueOf(sm.getHargaBeli()));

            // Lock field supplier & sepatu saat mode edit (cuma jumlah & harga yang boleh dikoreksi)
            txtStokSupplier.setEditable(false);
            txtStokSepatu.setEditable(false);
        }
    }//GEN-LAST:event_tableStokMasukMouseClicked

    private void btnDeleteStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStokActionPerformed
        if (selectedIdMasuk == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data stok yang mau dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Menghapus data ini akan mengurangi stok sepatu terkait. Yakin ingin melanjutkan?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean berhasil = stokMasukController.deleteStokMasuk(selectedIdMasuk);
            if (berhasil) {
                JOptionPane.showMessageDialog(this, "Data stok berhasil dihapus, stok sepatu telah disesuaikan.");
                clearFormStokMasuk();
                loadTableStokMasuk();
            }
        }
    }//GEN-LAST:event_btnDeleteStokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteStok;
    private javax.swing.JButton btnEditStok;
    private javax.swing.JButton btnInputSepatu;
    private javax.swing.JButton btnInputSupplier;
    private javax.swing.JButton btnTambahStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFormStok;
    private javax.swing.JPanel panelTableStok;
    private javax.swing.JTable tableStokMasuk;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtJumlahStok;
    private javax.swing.JTextField txtStokSepatu;
    private javax.swing.JTextField txtStokSupplier;
    // End of variables declaration//GEN-END:variables
}
